steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/fahrezaisnantodev/hospital20-api:$SHORT_SHA','.']
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/fahrezaisnantodev/hospital20-api:$SHORT_SHA']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [ 'run', 'deploy', 'hospital20-api', '--image=gcr.io/fahrezaisnantodev/hospital20-api:$SHORT_SHA', '--region=asia-southeast2', '--allow-unauthenticated']
